packages:
  - docs
  - crates/*
  - crates/native/npm/*
  - examples/*
  - packages/*
  - fixture

catalog:
  '@types/node': ^24.9.2
  tsdown: ^0.15.12
  typescript: ^5.9.3

onlyBuiltDependencies:
  - lefthook
