packages:
  - docs
  - crates/*
  - crates/native/npm/*
  - examples/*
  - packages/*
  - fixture

catalog:
  '@types/node': ^25.3.0
  tsdown: ^0.20.3
  typescript: ^5.9.3

onlyBuiltDependencies:
  - lefthook
