name = "mearie-examples-server"
main = "src/index.ts"

compatibility_flags = ["nodejs_compat"]
compatibility_date = "2025-10-25"

workers_dev = false
preview_urls = false

[observability]
enabled = true

[[routes]]
pattern = "api.mearie.dev"
custom_domain = true

[[rules]]
type = "Text"
globs = ["**/*.graphql"]
fallthrough = true
